# Generated by Django 4.2.5 on 2023-11-04 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=128)),
            ],
            options={
                'verbose_name': 'Incident type',
                'verbose_name_plural': 'Incident types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=64, null=True, verbose_name='Comment')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('open_incident_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Open time')),
                ('close_incident_time', models.DateTimeField(default=None, null=True, verbose_name='Close time')),
                ('acknowledge_time', models.DateTimeField(default=None, null=True, verbose_name='Acknowledge time')),
                ('incident_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident.incidenttype', verbose_name='Incident type')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ('open_incident_time', 'create_time'),
            },
        ),
    ]
