# Generated by Django 4.2.5 on 2023-11-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='incident',
        ),
        migrations.AlterModelTable(
            name='incidenttype',
            table='incident_type',
        ),
    ]
