# Generated by Django 4.2.5 on 2023-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_incident_table_alter_incidenttype_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='comment',
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.CharField(max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
