# Generated by Django 4.2.5 on 2023-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_remove_incident_comment_incident_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='style',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
