# Generated by Django 4.2.5 on 2023-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_incidenttype_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttype',
            name='name',
            field=models.TextField(max_length=128, unique=True),
        ),
    ]
